- name: Ensure HAProxy config directory exists
  file:
    path: "{{ haproxy_config_path | dirname }}"
    state: directory
    mode: "0755"

- name: Template HAProxy config file
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_path }}"
  notify: restart haproxy

- name: Pull HAProxy image
  docker_image:
    name: "{{ haproxy_image }}"
    tag: "{{ haproxy_version }}"
    source: pull

- name: Run HAProxy container
  docker_container:
    name: "{{ haproxy_container_name }}"
    image: "{{ haproxy_image }}:{{ haproxy_version }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ haproxy_port }}:{{ haproxy_port }}"
      - "{{ haproxy_stats_port }}:{{ haproxy_stats_port }}"
    volumes:
      - "{{ haproxy_config_path }}:/usr/local/etc/haproxy/haproxy.cfg:ro"

