---
- name: restart prometheus
  docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ image_name }}:{{ prometheus_version }}"
    state: started
    recreate: true
    restart_policy: unless-stopped
    published_ports:
      - "{{ prometheus_container_ports }}:{{ prometheus_container_ports }}"
    volumes:
      - "{{ docker_compose_path }}/config:/opt/bitnami/prometheus/conf"

